---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: graphite
  name: graphite-pvc
  namespace: benchmark
spec:
  storageClassName: cvs-extreme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
  name: grafana-pvc
  namespace: benchmark
spec:
  storageClassName: cvs-extreme
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vdbench
  name: vdbench-pvc
  namespace: benchmark
spec:
  storageClassName: cvs-standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
