---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vdbench
  name: vdbench-pvc
  namespace: benchmark
spec:
  storageClassName: gold
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
