---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: vdbench
  name: vdbench-pvc
  namespace: benchmark
spec:
  storageClassName: basic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vdbench
  name: vdbench
  namespace: benchmark
spec:
  replicas: 4
  selector:
    matchLabels:
      app: vdbench
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vdbench
    spec:
      volumes:
      - name: vdbench-vol
        persistentVolumeClaim:
          claimName: vdbench-pvc
      containers:
      - name: vdbench
        image: n1x0n/benchmark:7
        volumeMounts:
        - mountPath: "/benchmark"
          name: vdbench-vol
      restartPolicy: Always
