---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: grafana
  name: grafana-snap-clone
  namespace: benchmark
spec:
  storageClassName: gold
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  dataSource:
    name: x-snap
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io