---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fredrik
  namespace: default
spec:
  storageClassName: silver
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
