apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: select
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
  media: "ssd"
  provisioningType: "thin"
  snapshots: "true"
  selector: "type=select"

