{
 "title": "vdbench",
 "tags": [ "vdbench" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Vdbench Single Stats (Current)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.ioresp)"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.readresp)"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.writeresp)"
    }
   ]
  },
  {
   "title": "Std Dev Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "stdev(averageSeries(netapp.vdbench.*.ioresp), 5, 0.1)"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "target": "maxSeries(netapp.vdbench.*.ioresp)"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(netapp.vdbench.*.iorate)"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "target": "scale(scale(sumSeries(netapp.vdbench.*.mbstotal), 1024), 1024)"
    }
   ]
  },
  {
   "title": "Transfer Size (Avg)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.xfersize)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.cputotal)"
    }
   ]
  },
  {
   "title": "Read Ratio",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 4 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "target": "averageSeries(netapp.vdbench.*.readpct)"
    }
   ]
  },
  { "title": "Vdbench Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Vdbench Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(netapp.vdbench.*.ioresp), 'Latency')"
    },
    {
     "target": "alias(averageSeries(netapp.vdbench.*.readresp), 'Read Latency')"
    },
    {
     "target": "alias(averageSeries(netapp.vdbench.*.writeresp), 'Write Latency')"
    }
   ]
  },
  {
   "title": "Vdbench IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(netapp.vdbench.*.iorate), 'IOPS')"
    }
   ]
  },
  {
   "title": "Vdbench Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(scale(scale(netapp.vdbench.*.mbstotal, 1024), 1024)), 'Throughput')"
    },
    {
     "target": "alias(sumSeries(scale(scale(netapp.vdbench.*.mbsread, 1024), 1024)), 'Throughput (read)')"
    },
    {
     "target": "alias(sumSeries(scale(scale(netapp.vdbench.*.mbswrite, 1024), 1024)), 'Throughput (write)')"
    }
   ]
  },
  {
   "title": "Vdbench Hosts CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(netapp.vdbench.*.cputotal, 2)"
    }
   ]
  }
 ]
}