---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hacker
  name: hacker
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hacker
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hacker
    spec:
      volumes:
      - name: stolenprod
        nfs:
          server: 10.67.152.194
          path: /trident_pvc_8a122060_48f8_4d16_9a96_1c30a5286bbd
      - name: hacker-vol
        persistentVolumeClaim:
          claimName: vdbench-pvc
      containers:
      - name: hacker
        image: n1x0n/benchmark:7
        volumeMounts:
        - mountPath: "/benchmark"
          name: hacker-vol
        - mountPath: "/prod"
          name: stolenprod
      restartPolicy: Always
