---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: production
  name: production-pvc
  namespace: production
spec:
  storageClassName: gold
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti